# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791c2a5f447fbde9a6bb80e7427c7520306b9c4ede73fe8ec6da1f8bfacf18678b8f6cf11ca6d866250e68b37a0f12b06e793cfe7e0498436cb5a1fff6037936

test:
  secret_key_base: e6488840e82f6579de35fe10089992e63bc6b7a9ed6c62ecf69588233f9bf7fed1337fa0c32856f0383516d8eec0845b061a3b8add1502ff953126e48b5b01d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
